server:
  port: 9090

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  zipkin:
    # zipkin 服务器的地址
    base-url: http://localhost:9411
    # 关闭服务发现，否则 SpringCloud 会把 zipkin 的 url 当作服务名称
    discovery-client-enabled: false
    # 数据发送的方式：ACTIVEMQ RABBIT KAFKA WEB
    sender:
      type: web
  # 设置抽样采集率，默认 0.1（即10%），这里设置为 100%
  sleuth:
    sampler:
      probability: 1

myName:
  nacos-provider