server:
  port: 7070

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      # 指定 dashboard 地址
      transport:
        dashboard: localhost:8080
        # 启动该服务，会在应用程序的相应服务器上启动 HTTP Server，并且该服务器将于 Sentinel dashboard 进行交互
        port:
          8719
  zipkin:
    # zipkin 服务器的地址
    base-url: http://localhost:9411
    # 关闭服务发现，否则 SpringCloud 会把 zipkin 的 url 当作服务名称
    discovery-client-enabled: false
    # 数据发送的方式：ACTIVEMQ RABBIT KAFKA WEB
    sender:
      type: web
  # 设置抽样采集率，默认 0.1（即10%），这里设置为 100%
  sleuth:
    sampler:
      probability: 1

# 开启 sentinel 监控功能
feign:
  sentinel:
    enabled: true

myName:
  nacos-consumer
